inherit_from:
  - ./config/default.yml
  - ./config/rails.yml

Naming/FileName:
  Enabled: true
  Exclude:
    - "rubocop-github.gemspec"
    - "lib/rubocop-github.rb"
    - "lib/rubocop-github-rails.rb"
